### ISSUE TITLE
Commands and Command Manager

### ISSUE THREAD

**Issue by dehys** [devflask/RoboFlask#2]
Adding all necessary commands for the production.
Setting up a command manager as well as command handling.

**Comment by zp4rker** [comment]
might be handy to add a method to register multiple commands at the same time instead of doing:

```
registerCommands(new Ping());
registerCommands(new BotInfo());
registerCommands(new Kick());
registerCommands(new Ban());
registerCommands(new Unban());
```

you could do:
```
registerCommands(new Ping(), new BotInfo(), new Kick(), new Unban());
```

**Comment by dehys** [comment]
> might be handy to add a method to register multiple commands at the same time instead of doing:
> 
> ```
> registerCommands(new Ping());
> registerCommands(new BotInfo());
> registerCommands(new Kick());
> registerCommands(new Ban());
> registerCommands(new Unban());
> ```
> 
> you could do:
> 
> ```
> registerCommands(new Ping(), new BotInfo(), new Kick(), new Unban());
> ```

Thank you, added in  5439ed4
